### ISSUE TITLE
Support usage of absolute path for testRootPath

### ISSUE THREAD

**Issue by kgevorkyan** [cqfn/save#149]
According description of testRootPath `"Path to directory with tests (relative path from place, where save.properties is stored or absolute path)"` support logic of usage of absolute path
Now supported only relative https://github.com/cqfn/save/pull/148

**Comment by petertrr** [comment]
A sinppet on how we can get working directory in  `PlatformUtils` for linux:
```kotlin
import kotlinx.cinterop.ByteVar
import kotlinx.cinterop.allocArray
import kotlinx.cinterop.memScoped
import kotlinx.cinterop.toKString

val pwd: String = memScoped {
            platform.posix.getwd(allocArray<ByteVar>(platform.posix.PATH_MAX))!!.toKString()
        }
```

**Comment by kgevorkyan** [comment]
I think now it's redundant, after https://github.com/cqfn/save/issues/179, since now it is one entity (save.prop && testRootPath), which could be passed as relative either as absolute path, checked on `perfomAnalysisTest`, absolute paths worked fine
