### ISSUE TITLE
warn-plugin: Logic of line number calculation is buggy

### ISSUE THREAD

**Issue by petertrr** [cqfn/save#191]
* In `ignoreSaveComments=true` mode we should allow users to write numbers as in original file, but then run execCmd on filtered file and adjust line numbers (@akuleshov7 correct me if I got it wrong)
* In defaulktLineMode/placeholder mode calculate line number with adjustment to previous comments (subtract number of previous comment lines)

**Comment by akuleshov7** [comment]
We will remove `ignoreSaveComments` at all, and run without warnings, but will adjust line numbers

**Comment by petertrr** [comment]
How should we handle such cases:
```kotlin
// ;warn:$line Foo
// ;warn:$line Bar
val name = value
```
We can have `$line` point at the next line without warning comments (line 3 in this case), but it requires changes in how we handled it before. Or, `$line` can be line of the current comment, but `$line+1` immediately jumps to the next line. The latter seems too confusing to me.
