### ISSUE TITLE
LIT MODE: execution flags and run configuration

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save#230]
LIT contains two functionalities that we need to support:
1) https://github.com/cqfn/save/issues/221
2) RUN configuration:
``` // RUN: %check_clang_tidy %s huawei-unspecified-array-size %t ```

In this task we need to support execution flags and run configuration on plugin level (but functionality should be common for plugins...)

RUN configuration should be ignored during the calculation of line numbers.

**Comment by akuleshov7** [comment]
This issue should also cover cases when we would like to add something in the end of our execution command AFTER file names.

**Comment by petertrr** [comment]
Discussed and decided to do the following:
`execFlags` in `save.toml` can be extended with values from the file:
```koltin
// RUN: extraFlagsBefore=stuff, extraFlagsAfter=stuff2
```
and then these variables can be used as placeholders:
```toml
execFlags = "-F $extraFlagsBefore $files $extraFlagsAfter"
```

**Comment by akuleshov7** [comment]
LIT can contain SEVERAL RUN commands on the same file... Probably we should create an issue for it
