### ISSUE TITLE
Aggregate test results by pass or fail

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save#249]
Now test results are not aggregated. May be we could support some kind of an adaptor that would be able to collect and aggregate test results. For example, in Idea there is a possibility to show only `failed` tests. Could be very useful

**Comment by petertrr** [comment]
I'm not sure, what we should do for this. Integrations like IDE or plugins for CI or build systems will most probably need some customization, and for that we allow writing custom reporters. Reporters are triggered on each event, so they can aggregate them how they want. We can make sort of a base statistics-aware reporter with built-in counter (but I think that in the scope of #251), so not sure what kind of adapter will help here.

**Comment by akuleshov7** [comment]
When I was testing clang-tidy - I was not able to filter failed tests to understand issues in save. We need to get ONLY failed tests in PLAIN mode. It will be extremely useful.

**Comment by petertrr** [comment]
As discussed, decided to implement functionality for `PLAIN` reporter to show only failed tests. This can be achieved by implementing a several subtype of plain reporter `plain-failed`
