### ISSUE TITLE
Error: Couldn't find `suiteName` in [general] section of `undefined_toml_location` config.

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save#267]
We should have proper logging instead of `undefined_toml_location`

How to reproduce:
In warn-dir/save.toml delete:
```
    suiteName = "warnings"
```

**Comment by akuleshov7** [comment]
Also please change the logic: you need to raise a warning ONLY when the suite name is missing on the test resource BEFORE the exeution, not on the validation step:
```
Error: Couldn't find `suiteName` in [general] section of `undefined_toml_location` config.
Current configuration: execCmd=java -jar ktlint -R diktat.jar, tags=[warn], description=Test for directory mode, suiteName=null, excludedTests=null, expectedWarningsPattern=null, runConfigPattern=null
Please provide it in this, or at least in one of the parent configs.

```

**Comment by kgevorkyan** [comment]
Those problems occurred because previously we validated all configs, even without test resources
