### ISSUE TITLE
Save should be able to process test results stored in a file 

### ISSUE THREAD

**Issue by orchestr7** [cqfn/save#295]
If test results are provided by the tested tool, save should be able to process and compare these results.

Right now we are simply reading stdout in warnPLugin:
```
val executionResulr = try {
    pb.exec()
}
```

Instead of this in case a special option with a value `testToolResFileOutput = /dir/bin/blabla/result.file` we should do the following:
1) execute the command in `pb.exec` 
2) read the file `/dir/bin/blabla/result.file` and collect actual warnings from it

**Comment by petertrr** [comment]
To work with absolute paths in native `okio.PosixFileSystem#canonicalize` can be used
