### ISSUE TITLE
Detekt does not check the project

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save#59]
It looks like detekt is not checking the project.
I think so, because:
1) I have broken the formatting and it does not trigger an error
2) detektAll works for several seconds

**Comment by petertrr** [comment]
This is because we use KMP and, apparently, detekt doesn't detect (pun unintended) correct soruce directories

**Comment by petertrr** [comment]
Actually, they have added support for KMP project out of the box in 1.16, but we haven't adopted that version yet because of some strange errors. I'll dig into this again in detail and write the results here.
