### ISSUE TITLE
Add a method for the validation of Config sections in toml configuration

### ISSUE THREAD

**Issue by akuleshov7** [cqfn/save#86]
We found this on 'tags' section. It is not needed on the high levels of the tree structure. 
We need to validate ONLY config THAT will be used for running tests (and not validate configs from other high levels)

**Comment by akuleshov7** [comment]
Also, under this task you need to remove "required init blocks" in plugin data classes from corresponding data classes.

**Comment by kgevorkyan** [comment]
It also should be provided logic for default values for nullable fields, since in stage of merging we can do this

**Comment by akuleshov7** [comment]
you should validate **ONLY** those configs that contain any test resources
