### ISSUE TITLE
Support batchMode option in plugins

### ISSUE THREAD

**Issue by petertrr** [cqfn/save#88]
It controlls, whether execCmd transforms one file at a time or multiple as a batch.

**Comment by akuleshov7** [comment]
As we discussed - it should be not a boolean variable, but some int. Instead batchMode we should have 'batchSize = '

**Comment by akuleshov7** [comment]
Also support batch separator (, ; / space,e.t.c)

**Comment by akuleshov7** [comment]
Do not forget to change warningsInputPattern and add fileNameCaptureGroup to warn plugin
